name: Fetch BigQuery Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: create service-secrets.json
      run: |
        echo "$SERVICE_SECRETS" > service-secrets.json
      env:
        SERVICE_SECRETS: ${{ secrets.SERVICE_SECRETS }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e . -c requirements.txt
        pip install traceback-with-variables

    - name: Build the dashboard
      run: |
        traceback-with-variables napari_dashboard.big_query_update
      env:
        PEPY_KEY: ${{ secrets.PEPY_KEY }}
        GH_TOKEN_: ${{ secrets.GITHUB_TOKEN }}
        # I'm using GH_TOKEN_ because using GITHUB_TOKEN during development crash gh app

    - name: Deploy Dashboard
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./webpage
        publish_branch: gh_pages

    - name: Send a stream message
      uses: zulip/github-actions-zulip/send-message@v1
      with:
        api-key: ${{ secrets.ZULIP_API_KEY }}
        email: "dashboard-bot@napari.zulipchat.com"
        organization-url: "https://napari.zulipchat.com"
        to: "metrics and analytics"
        type: "stream"
        topic: "Google big query download"
        content: "Google big query finished successful"

    - name: Send a stream message
      uses: zulip/github-actions-zulip/send-message@v1
      if: ${{ failure() }}
      with:
        api-key: ${{ secrets.ZULIP_API_KEY }}
        email: "dashboard-bot@napari.zulipchat.com"
        organization-url: "https://napari.zulipchat.com"
        to: "metrics and analytics"
        type: "stream"
        topic: "Google big query download"
        content: "Google big query failed"
